// Obsidian → mdview 主题转换
// Obsidian 主题用 .markdown-preview-view / .markdown-rendered 等选择器，
// 同时大量依赖 CSS 变量（--background-primary 等）。我们做两件事：
// 1. 选择器映射到 #mdview-output
// 2. 保留所有 CSS 变量定义（让用户在 mdview 里用 :root 注入即可）
export interface ObsidianImportResult {
  css: string;
  meta: {
    id: string;
    name: string;
    version: string;
    author: string;
    description: string;
    sourceFormat: 'obsidian';
  };
  warnings: string[];
}

const SELECTOR_MAP: Array<[RegExp, string]> = [
  // 主预览容器
  [/\.markdown-preview-view\b/g, '#mdview-output'],
  [/\.markdown-rendered\b/g, '#mdview-output'],
  [/\.markdown-source-view\b/g, '#mdview-output'],
  // 内联代码 / 代码块
  [/\.HyperMD-codeblock\b/g, '#mdview-output pre'],
  [/\.cm-inline-code\b/g, '#mdview-output code'],
  // 标题
  [/\.cm-header-(\d)\b/g, '#mdview-output h$1'],
  // 链接
  [/\.internal-link\b/g, '#mdview-output a'],
  [/\.external-link\b/g, '#mdview-output a'],
  // callout
  [/\.callout\b/g, '#mdview-output .mdv-callout'],
  [/\.callout-title\b/g, '.mdv-callout-title'],
  // 任务列表
  [/\.task-list-item\b/g, '#mdview-output li.task-list-item'],
];

const DROP_RULES = [
  /\.workspace/, // Obsidian 工作区 chrome
  /\.titlebar/, // 标题栏
  /\.modal-/, // 模态对话框
  /\.suggestion-/, // 自动补全
  /\.menu/, // 菜单
  /\.cm-cursor/, // 编辑器光标
  /\.theme-light\s*\.mod-/, // Obsidian 私有 mod- 前缀
];

export function importObsidianTheme(
  cssText: string,
  options: { id: string; name?: string; author?: string } = { id: 'imported-obsidian' },
): ObsidianImportResult {
  const warnings: string[] = [];
  let css = cssText;

  for (const [from, to] of SELECTOR_MAP) {
    css = css.replace(from, to);
  }
  css = stripRulesMatching(css, DROP_RULES, warnings);

  const header =
    `/* mdview theme converted from Obsidian source.\n` +
    ` * Auto-generated by @mdview/importer.\n` +
    ` * Note: Obsidian themes rely heavily on CSS variables under .theme-light / .theme-dark.\n` +
    ` * If your converted theme looks blank, the variables aren't propagating —\n` +
    ` * either move them to :root or wrap #mdview-output in a body class.\n` +
    ` */\n\n`;

  return {
    css: header + css.trim() + '\n',
    meta: {
      id: options.id,
      name: options.name ?? options.id,
      version: '0.0.1',
      author: options.author ?? 'unknown',
      description: 'Imported from Obsidian theme.',
      sourceFormat: 'obsidian',
    },
    warnings,
  };
}

// 共用底层工具，与 typora.ts 同一份逻辑（避免循环导入直接复制）
function stripRulesMatching(
  css: string,
  dropPatterns: RegExp[],
  warnings: string[],
): string {
  const out: string[] = [];
  let i = 0;
  const n = css.length;
  while (i < n) {
    if (css.startsWith('/*', i)) {
      const end = css.indexOf('*/', i + 2);
      if (end < 0) {
        out.push(css.slice(i));
        break;
      }
      out.push(css.slice(i, end + 2));
      i = end + 2;
      continue;
    }
    const braceOpen = findUnquoted(css, '{', i);
    if (braceOpen < 0) {
      out.push(css.slice(i));
      break;
    }
    const braceClose = findMatchingClose(css, braceOpen);
    if (braceClose < 0) {
      out.push(css.slice(i));
      break;
    }
    const selector = css.slice(i, braceOpen).trim();
    const fullRule = css.slice(i, braceClose + 1);
    if (dropPatterns.some((p) => p.test(selector))) {
      warnings.push(`Dropped rule: ${selector.slice(0, 80)}`);
    } else {
      out.push(fullRule);
    }
    i = braceClose + 1;
  }
  return out.join('');
}

function findUnquoted(css: string, target: string, from: number): number {
  let i = from;
  let inStr: string | null = null;
  while (i < css.length) {
    const ch = css[i]!;
    if (inStr) {
      if (ch === '\\') { i += 2; continue; }
      if (ch === inStr) inStr = null;
    } else {
      if (ch === '"' || ch === "'") inStr = ch;
      else if (ch === target) return i;
    }
    i++;
  }
  return -1;
}

function findMatchingClose(css: string, openPos: number): number {
  let depth = 0;
  let i = openPos;
  let inStr: string | null = null;
  while (i < css.length) {
    const ch = css[i]!;
    if (inStr) {
      if (ch === '\\') { i += 2; continue; }
      if (ch === inStr) inStr = null;
    } else {
      if (ch === '"' || ch === "'") inStr = ch;
      else if (ch === '{') depth++;
      else if (ch === '}') {
        depth--;
        if (depth === 0) return i;
      }
    }
    i++;
  }
  return -1;
}
