// Typora → mdview 主题转换
// 核心思路：把 Typora 的根选择器（#write）映射到 mdview 的 #mdview-output，
// 同时改写一些 Typora 私有选择器为 mdview 等价选择器。
// 不能 100% 自动 —— 部分高度定制的 Typora 主题仍需人工微调，
// 但对绝大多数公开主题（Diaphora / Lapis / Drake 等）能给到一份可直接用的 90% 完成度。

export interface ImportResult {
  /** 转换后的 CSS 内容 */
  css: string;
  /** 自动生成的 theme.json 候选元数据 */
  meta: {
    id: string;
    name: string;
    version: string;
    author: string;
    description: string;
    sourceFormat: 'typora';
  };
  /** 转换过程中跳过 / 警告的条目，便于人工补丁 */
  warnings: string[];
}

/**
 * Typora 选择器映射 —— 高优先级在前，按字符串替换顺序应用
 * 注意：保持顺序，避免短前缀先匹配把后面长选择器破坏掉
 */
const SELECTOR_MAP: Array<[RegExp, string]> = [
  // 根容器
  [/#write\b/g, '#mdview-output'],
  [/\.markdown-here-wrapper\b/g, '#mdview-output'],
  // Typora 标题样式
  [/\.md-end-block/g, '.mdview-block'],
  // 代码 fence
  [/\.md-fences\b/g, '#mdview-output pre'],
  [/\.cm-s-inner\b/g, '#mdview-output pre code'],
  [/\.md-code-block\b/g, '#mdview-output pre'],
  // 任务列表
  [/\.task-list-item\b/g, 'li.task-list-item'],
  // 引用块
  [/\.md-blockquote\b/g, '#mdview-output blockquote'],
  // 表格
  [/\.md-table\b/g, '#mdview-output table'],
  // 图片
  [/\.md-image\b/g, '#mdview-output img'],
  // 行内代码
  [/\.md-inline-code\b/g, '#mdview-output code'],
  // YAML front matter（Typora 把它显示在文档顶端，mdview 不展示）
  [/\.md-meta-block\b/g, '.mdview-frontmatter-display'],
];

/** 删除掉的 Typora 私有选择器 —— 它们引用了 Typora 编辑态 DOM，mdview 渲染态没有 */
const DROP_RULES = [
  /\.cm-/, // CodeMirror 编辑器内部类
  /\.md-toc\b/, // Typora TOC 边栏
  /\.md-source-view/, // Typora source 模式
  /\.typora-/, // Typora 自家 chrome
  /\.show-content\s/, // Typora 显示开关
];

export function importTyporaTheme(
  cssText: string,
  options: { id: string; name?: string; author?: string } = { id: 'imported' },
): ImportResult {
  const warnings: string[] = [];
  let css = cssText;

  // 1. 选择器映射
  for (const [from, to] of SELECTOR_MAP) {
    css = css.replace(from, to);
  }

  // 2. 删除引用了 Typora 编辑态 DOM 的规则
  css = stripRulesMatching(css, DROP_RULES, warnings);

  // 3. 注入注释头
  const header =
    `/* mdview theme converted from Typora source.\n` +
    ` * Auto-generated by @mdview/importer.\n` +
    ` * If anything looks off, manually tweak this file.\n` +
    ` */\n\n`;

  return {
    css: header + css.trim() + '\n',
    meta: {
      id: options.id,
      name: options.name ?? options.id,
      version: '0.0.1',
      author: options.author ?? 'unknown',
      description: 'Imported from Typora theme.',
      sourceFormat: 'typora',
    },
    warnings,
  };
}

/**
 * 极简 CSS 规则解析：以最外层 `}` 为边界切片，丢掉 selector 中包含 dropList 的规则。
 * 不处理 nested at-rules（@media 内部 nested 规则会被整体保留），对 Typora 主题足够。
 */
function stripRulesMatching(css: string, dropPatterns: RegExp[], warnings: string[]): string {
  const out: string[] = [];
  let i = 0;
  const n = css.length;
  const inComment = false;

  while (i < n) {
    // 跳过注释
    if (!inComment && css.startsWith('/*', i)) {
      const end = css.indexOf('*/', i + 2);
      if (end < 0) {
        out.push(css.slice(i));
        break;
      }
      out.push(css.slice(i, end + 2));
      i = end + 2;
      continue;
    }
    // 找下一个 `{`
    const braceOpen = findUnquoted(css, '{', i);
    if (braceOpen < 0) {
      out.push(css.slice(i));
      break;
    }
    // 找匹配的 `}`
    const braceClose = findMatchingClose(css, braceOpen);
    if (braceClose < 0) {
      out.push(css.slice(i));
      break;
    }
    const selectorBlock = css.slice(i, braceOpen);
    const selector = selectorBlock.trim();
    const fullRule = css.slice(i, braceClose + 1);

    // 测试 selector 是否包含 drop 模式
    const shouldDrop = dropPatterns.some((p) => p.test(selector));
    if (shouldDrop) {
      warnings.push(`Dropped rule: ${truncate(selector, 80)}`);
    } else {
      out.push(fullRule);
    }
    i = braceClose + 1;
  }

  return out.join('');
}

/** 找到 css 中下一个未在 string 中的字符 */
function findUnquoted(css: string, target: string, from: number): number {
  let i = from;
  let inStr: string | null = null;
  while (i < css.length) {
    const ch = css[i]!;
    if (inStr) {
      if (ch === '\\') {
        i += 2;
        continue;
      }
      if (ch === inStr) inStr = null;
    } else {
      if (ch === '"' || ch === "'") inStr = ch;
      else if (ch === target) return i;
    }
    i++;
  }
  return -1;
}

/** 平衡 `{}` 找到匹配的右括号位置 */
function findMatchingClose(css: string, openPos: number): number {
  let depth = 0;
  let i = openPos;
  let inStr: string | null = null;
  while (i < css.length) {
    const ch = css[i]!;
    if (inStr) {
      if (ch === '\\') {
        i += 2;
        continue;
      }
      if (ch === inStr) inStr = null;
    } else {
      if (ch === '"' || ch === "'") inStr = ch;
      else if (ch === '{') depth++;
      else if (ch === '}') {
        depth--;
        if (depth === 0) return i;
      }
    }
    i++;
  }
  return -1;
}

function truncate(s: string, n: number): string {
  if (s.length <= n) return s;
  return s.slice(0, n - 1) + '…';
}
